### ISSUE TITLE
希望尽快上传所有训练的的配置文件

### ISSUE THREAD

**Issue by Idol-Dou2021** [JianhaoChen-nju/TSDRE#1]
亲爱的开发者您好，我对您的研究非常感兴趣，希望您能尽快上传所有的文件，以供我们接下来进行研究，非常感谢您。或者发给我的邮箱也行：461289907@qq.com，万分感谢您

**Comment by jackou2077** [comment]
TSDRE需要自己搭建一个pipeline
1. 利用GPT，Llama等大模型分解，相关prompt已经上传
2. 使用Flan-T5进行训练，从huggingface上下载后直接训练即可，使用的是默认超参数，硬件配置在附录有说
  - 具体使用的是trainer api进行训练，可参考https://huggingface.co/docs/transformers/zh/main_classes/trainer

**Comment by Idol-Dou2021** [comment]
> TSDRE需要自己搭建一个管道
> 
> 1. 利用GPT，Llama等大模型划分，相关提示已经上传
> 2. 使用Flan-T5进行训练，从huggingface上下载后直接训练即可，使用的是默认超参数，硬件配置在附录中有说
> 
> * 具体使用是trainer api进行训练，可参考https://huggingface.co/docs/transformers/zh/main_classes/trainer

好的，谢谢您的回复！
